blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/nuclearfantasyfootball
    about: Check the NuclearFF README for general information.
  - name: Discord Community
    url: https://discord.gg/9sJQ4yYkkF
    about: Join the Discord community for general questions, ideas, or help.