name: Feature Request
description: Suggest a new feature or improvement for Nuclear Fantasy Football tools.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a feature request! Fill out all sections the best you can to help us understand and evaluate.

  - type: input
    id: package
    attributes:
      label: Package for Enhancement
      description: What package or tool does this feature request refer to?
      placeholder: e.g., sena, otis, gerald

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem and why this feature is a need or want.
      placeholder: |
        What problem would this feature solve? What new capability or improved functionality would it provide? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the proposed solution and what the solution considers.
      placeholder: |
        Describe your idea clearly. Provide clear and detailed discussion.
        Examples, code snippets, mockups, and links to references are helpful.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Additional context, discussion, or alternatives considered.
      placeholder: |
        Additional solutions or pathways considered. Links to related issues, discussions, etc. Links with references to useful resources.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the urgency to develop the feature?
      options:
        - Nice-to-Have - Feature is an add-on or bonus and not essential.
        - Need-to-Have - Feature needs to be developed in the future.
        - Must-Have - Feature is essential and needs to be scheduled.
        - Critical - Feature is critical and highest priority.
      default: Nice-to-Have - Feature is an add-on or bonus and not essential.
